# Generated by Django 3.0.2 on 2020-01-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_data',
        ),
    ]
