# Generated by Django 3.0.2 on 2020-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
