# Generated by Django 3.0.2 on 2020-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='yearOfEstablishment',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
