# Generated by Django 2.2.9 on 2020-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_college_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('article', models.CharField(default=None, max_length=1000)),
                ('emailAdd', models.EmailField(default=None, max_length=40, unique=True)),
                ('collegeName', models.CharField(max_length=1000)),
                ('dateOfPublish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
