# Generated by Django 2.2.9 on 2020-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_consensus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consensus',
            name='emailAdd',
            field=models.EmailField(default=None, max_length=40),
        ),
    ]
