# Generated by Django 2.2.9 on 2020-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20200119_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(default=None, max_length=1000)),
                ('noticeBody', models.CharField(default=None, max_length=10000)),
                ('emailAdd', models.EmailField(default=None, max_length=40)),
                ('collegeName', models.CharField(max_length=1000)),
                ('dateOfPublish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
