# Generated by Django 3.0.2 on 2020-01-12 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=None, max_length=30)),
                ('middleName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(default=None, max_length=30)),
                ('mobileNo', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(default=None, max_length=500)),
                ('emailAdd', models.EmailField(default=None, max_length=40, unique=True)),
                ('collegeAdmissionId', models.CharField(default=None, max_length=300)),
                ('currentWorkStatus', models.CharField(default=None, max_length=300)),
                ('AnnualIncome', models.IntegerField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(default=None, max_length=300)),
                ('pincode', models.IntegerField(default=None)),
                ('gender', models.CharField(default=None, max_length=15)),
                ('degreePersuedFromClg', models.CharField(default=None, max_length=100)),
                ('YearOfCompletion', models.CharField(default=None, max_length=10)),
                ('CollegeName', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(default=None, max_length=100)),
                ('verificationStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Alumini Info',
            },
        ),
    ]
