# Generated by Django 3.0.2 on 2020-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='College/media/default.jpg', upload_to='Student/media'),
        ),
    ]
